export const products = [
    {
        _id: '6212',
        name: 'Samsung Galaxy',
        image: '/images/flip.jpg',
        description:
        'lorem Ipsum',
        brand: 'Apple',
        category: 'Electronics',
        price: 787.50,
        rating: 5,
        numReviews: 1,
        isNew: true,
        reviews: [],
        stock: 7,
    },
    {
        _id: '6213',
        name: 'Iphon 12 Pro',
        image: '/images/a73.jpg',
        description:
        'lorem Ipsum',
        brand: 'Apple',
        category: 'Electronics',
        price: 987.50,
        rating: 5,
        numReviews: 1,
        isNew: true,
        reviews: [],
        stock: 7,
    },
    {
        _id: '6214',
        name: 'Apple Watch',
        image: '/images/apple-watch.jpg',
        description:
        'lorem Ipsum',
        brand: 'Apple',
        category: 'Electronics',
        price: 347.50,
        rating: 4,
        numReviews: 1,
        isNew: false,
        reviews: [],
        stock: 0,
    },
    {
        _id: '6215',
        name: 'iphone',
        image: '/images/iphone.jpg',
        description:
        'lorem Ipsum',
        brand: 'Apple',
        category: 'Electronics',
        price: 987.48,
        rating: 5,
        numReviews: 1,
        isNew: false,
        reviews: [],
        stock: 12,
    },
]