export const products = [
    {
        _id: '6212',
        name: 'Samsung Galaxy',
        image: '/images/flip.jpg',
        description:
        'lorem Ipsum',
        brand: 'Apple',
        category: 'Electronics',
        price: 787.50,
        compare_at_price: 900.25,
        rating: 5,
        numReviews: 60,
        isNew: false,
        reviews: [],
        stock: 7,
    },
    {
        _id: '6213',
        name: 'Iphon 12 Pro',
        image: '/images/a73.jpg',
        description:
        'lorem Ipsum',
        brand: 'Apple',
        category: 'Electronics',
        price: 917.55,
        rating: 4,
        numReviews: 90,
        isNew: true,
        reviews: [],
        stock: 7,
    },
    {
        _id: '6214',
        name: 'Apple Watch',
        image: '/images/apple-watch.jpg',
        description:
        'lorem Ipsum',
        brand: 'Apple',
        category: 'Electronics',
        price: 347.50,
        compare_at_price: 575.60,
        rating: 2,
        numReviews: 8,
        isNew: false,
        reviews: [],
        stock: 0,
    },
    {
        _id: '6218',
        name: 'Microphone',
        image: '/images/shure-mv7.jpg',
        description:
        'lorem Ipsum',
        brand: 'Apple',
        category: 'Electronics',
        price: 497.35,
        rating: 1,
        numReviews: 1,
        isNew: true,
        reviews: [],
        stock: 6,
    },
    {
        _id: '6216',
        name: 's4prowatch',
        image: '/images/s4prowatch.jpg',
        description:
        'lorem Ipsum',
        brand: 'Apple',
        category: 'Electronics',
        price: 590.99,
        compare_at_price: 987.60,
        rating: 5,
        numReviews: 38,
        isNew: false,
        reviews: [],
        stock: 0,
    },
    {
        _id: '6215',
        name: 'Iphone',
        image: '/images/iphone.jpg',
        description:
        'lorem Ipsum',
        brand: 'Apple',
        category: 'Electronics',
        compare_at_price: 660.25,
        price: 587.48,
        rating: 4,
        numReviews: 23,
        isNew: true,
        reviews: [],
        stock: 12,
    },
    {
        _id: '6217',
        name: 'Microphone',
        image: '/images/deity-vo-7u-boom.webp',
        description:
        'lorem Ipsum',
        brand: 'Apple',
        category: 'Electronics',
        price: 530.99,
        rating: 5,
        numReviews: 1,
        isNew: false,
        reviews: [],
        stock: 12,
    },
    
    {
        _id: '6219',
        name: 'Ipad',
        image: '/images/tab.jpg',
        description:
        'lorem Ipsum',
        brand: 'Apple',
        category: 'Electronics',
        price: 687.55,
        compare_at_price: 810.45,
        rating: 3,
        numReviews: 10,
        isNew: true,
        reviews: [],
        stock: 12,
    },
    {
        _id: '6220',
        name: 'Tablet',
        image: '/images/tablet.jpg',
        description:
        'lorem Ipsum',
        brand: 'Apple',
        category: 'Electronics',
        price: 380.25,
        rating: 4,
        numReviews: 80,
        isNew: false,
        reviews: [],
        stock: 0,
    },
    {
        _id: '6221',
        name: 's4watch',
        image: '/images/s4watch.jpg',
        description:
        'lorem Ipsum',
        brand: 'Apple',
        category: 'Electronics',
        price: 567.40,
        rating: 3,
        numReviews: 45,
        isNew: false,
        reviews: [],
        stock: 8,
    },
]